# Use a lightweight Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy and install dependencies
COPY ./sensor-data-generator/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ./sensor-data-generator .

# Define the command to run the application
CMD ["python", "generator.py"]