name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push weather-app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.weather-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/weather-app:latest
      
      - name: Build and push sensor-generator
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.sensor-generator
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sensor-generator:latest
